export const GET_DATA = 'GET_DATA';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_FLAG = 'GET_FLAG';
export const SET_CARD_LOADING = 'SET_CARD_LOADING';
export const SET_LIST_LOADING = 'SET_LIST_LOADING';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';